version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chess_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/docker-entrypoint-initdb.d


